/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package liquidacionsueldos;

/**
 *
 * @author User
 */
public class formulario extends javax.swing.JFrame {

    arregloEmpleados arreglo;
    public formulario() {
        initComponents();
        arreglo=new arregloEmpleados();
        BtnReportes.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupTipos = new javax.swing.ButtonGroup();
        LblTitulo = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        LblLegajo = new javax.swing.JLabel();
        TxtLegajo = new javax.swing.JTextField();
        LblSueldoBasico = new javax.swing.JLabel();
        TxtSueldoBasico = new javax.swing.JTextField();
        LblDiasTrabajados = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CheckPresentismo = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        TxtVentas = new javax.swing.JTextField();
        BtnCargar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RadioAdm = new javax.swing.JRadioButton();
        RadioObrero = new javax.swing.JRadioButton();
        RadioVendedor = new javax.swing.JRadioButton();
        BtnReportes = new javax.swing.JButton();
        TxtDiasTrabajados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblTitulo.setText("DATOS EMPLEADOS");

        LblNombre.setText("NOMBRE COMPLETO");

        LblLegajo.setText("LEGAJO");

        LblSueldoBasico.setText("SUELDO BASICO");

        LblDiasTrabajados.setText("DIAS TRABAJADOS");

        jLabel1.setText("PRESENTISMO");

        jLabel2.setText("TOTAL VENTAS");

        BtnCargar.setText("CARGAR DATOS");
        BtnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarActionPerformed(evt);
            }
        });

        jLabel3.setText("TIPO DE EMPLEADO");

        GroupTipos.add(RadioAdm);
        RadioAdm.setText("ADMINISTRATIVO");
        RadioAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAdmActionPerformed(evt);
            }
        });

        GroupTipos.add(RadioObrero);
        RadioObrero.setText("OBRERO");
        RadioObrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioObreroActionPerformed(evt);
            }
        });

        GroupTipos.add(RadioVendedor);
        RadioVendedor.setText("VENDEDOR");
        RadioVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioVendedorActionPerformed(evt);
            }
        });

        BtnReportes.setText("REPORTES");
        BtnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReportesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(BtnCargar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnReportes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblLegajo)
                                .addGap(18, 18, 18)
                                .addComponent(TxtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LblSueldoBasico)
                                    .addGap(37, 37, 37)
                                    .addComponent(TxtSueldoBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LblNombre)
                                    .addGap(18, 18, 18)
                                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(RadioAdm)
                                .addGap(18, 18, 18)
                                .addComponent(RadioObrero)
                                .addGap(42, 42, 42)
                                .addComponent(RadioVendedor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblDiasTrabajados)
                                .addGap(18, 18, 18)
                                .addComponent(TxtDiasTrabajados, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckPresentismo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(44, 44, 44)
                                .addComponent(TxtVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(LblTitulo)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RadioAdm)
                    .addComponent(RadioObrero)
                    .addComponent(RadioVendedor))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblLegajo)
                    .addComponent(TxtLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombre)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSueldoBasico)
                    .addComponent(TxtSueldoBasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblDiasTrabajados)
                        .addComponent(jLabel1)
                        .addComponent(TxtDiasTrabajados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CheckPresentismo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCargar)
                    .addComponent(BtnReportes))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarActionPerformed
        
        if(RadioAdm.isSelected())
        {
            int legajo=Integer.parseInt(TxtLegajo.getText());
            String nombre=TxtNombre.getText();
            double basico=Double.parseDouble(TxtSueldoBasico.getText());
            boolean presentismo=false;
            if(CheckPresentismo.isSelected()){presentismo=true;}
            
            Administrativo a=new Administrativo(legajo,nombre,basico,presentismo);
            arreglo.agregarEmpleadoNuevo(a);
                       
        }
        else if(RadioObrero.isSelected())
        {
            int legajo=Integer.parseInt(TxtLegajo.getText());
            String nombre=TxtNombre.getText();
            double basico=Double.parseDouble(TxtSueldoBasico.getText());
            int dias=Integer.parseInt(TxtDiasTrabajados.getText());
            
            Obrero o=new Obrero(legajo,nombre,basico,dias);
            arreglo.agregarEmpleadoNuevo(o);            
        }
        else
        {
            int legajo=Integer.parseInt(TxtLegajo.getText());
            String nombre=TxtNombre.getText();
            double basico=Double.parseDouble(TxtSueldoBasico.getText());
            int ventas=Integer.parseInt(TxtVentas.getText());
            
            Vendedor v=new Vendedor(legajo,nombre,basico,ventas);
            arreglo.agregarEmpleadoNuevo(v);
            BtnReportes.setEnabled(true);
            
        }
        this.limpiarCampos();
    }//GEN-LAST:event_BtnCargarActionPerformed

    
    public void limpiarCampos()
    {
        TxtLegajo.setText("");
        TxtNombre.setText("");
        TxtSueldoBasico.setText("");
        TxtVentas.setText("");
        TxtDiasTrabajados.setText("");
        CheckPresentismo.setSelected(false);
    }
    private void BtnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReportesActionPerformed
        new Reportes(arreglo).setVisible(true);
    }//GEN-LAST:event_BtnReportesActionPerformed

    private void RadioAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAdmActionPerformed
        TxtDiasTrabajados.setEnabled(false);
        TxtVentas.setEnabled(false);
        CheckPresentismo.setEnabled(true);
        
    }//GEN-LAST:event_RadioAdmActionPerformed

    private void RadioObreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioObreroActionPerformed
       CheckPresentismo.setEnabled(false);
        TxtVentas.setEnabled(false);
        TxtDiasTrabajados.setEnabled(true);
    }//GEN-LAST:event_RadioObreroActionPerformed

    private void RadioVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioVendedorActionPerformed
        TxtDiasTrabajados.setEnabled(false);
        CheckPresentismo.setEnabled(false);
        TxtVentas.setEnabled(true);
    }//GEN-LAST:event_RadioVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCargar;
    private javax.swing.JButton BtnReportes;
    private javax.swing.JCheckBox CheckPresentismo;
    private javax.swing.ButtonGroup GroupTipos;
    private javax.swing.JLabel LblDiasTrabajados;
    private javax.swing.JLabel LblLegajo;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblSueldoBasico;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JRadioButton RadioAdm;
    private javax.swing.JRadioButton RadioObrero;
    private javax.swing.JRadioButton RadioVendedor;
    private javax.swing.JTextField TxtDiasTrabajados;
    private javax.swing.JTextField TxtLegajo;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtSueldoBasico;
    private javax.swing.JTextField TxtVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

}
