
package liquidacionsueldos;

public class Reportes extends javax.swing.JFrame {

    private arregloEmpleados arreglo1;
    
    public Reportes(arregloEmpleados arreglo) {
        initComponents();
        arreglo1=arreglo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListEmpleados = new javax.swing.JList();
        TxtTotal = new javax.swing.JTextField();
        LblMenorSueldo = new javax.swing.JLabel();
        TxtPromObreros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CmbTipos = new javax.swing.JComboBox<>();
        TxtSumaSueldos = new javax.swing.JTextField();
        BtnListado = new javax.swing.JButton();
        BtnCalcular = new javax.swing.JButton();
        BtnTotalGral = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        BtnPromObreros = new javax.swing.JButton();
        TxtMenorSueldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelTitulo.setText("LIQUIDACION SUELDOS");

        jScrollPane1.setViewportView(ListEmpleados);

        LblMenorSueldo.setText("DATOS DEL EMPLEADO CON MENOR SUELDO");

        jLabel4.setText("SUMA DE SUELDOS POR TIPO DE EMPLEADO");

        CmbTipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrativos", "Obreros", "Vendedores" }));

        BtnListado.setText("LISTADO EMPLEADOS");
        BtnListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnListadoActionPerformed(evt);
            }
        });

        BtnCalcular.setText("CALCULAR");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        BtnTotalGral.setText("TOTAL GENERAL ");
        BtnTotalGral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTotalGralActionPerformed(evt);
            }
        });

        BtnBuscar.setText("BUSCAR");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        BtnPromObreros.setText("PROMEDIO DE SUELDOS DE OBREROS");
        BtnPromObreros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPromObrerosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnPromObreros)
                        .addGap(29, 29, 29)
                        .addComponent(TxtPromObreros, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TxtMenorSueldo)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(CmbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(BtnCalcular))
                                .addComponent(LblMenorSueldo)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BtnTotalGral)
                                    .addGap(25, 25, 25)
                                    .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(LabelTitulo)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnListado))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtSumaSueldos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnBuscar))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(LabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(BtnListado)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CmbTipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtSumaSueldos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnTotalGral))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMenorSueldo)
                    .addComponent(BtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtMenorSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnPromObreros)
                    .addComponent(TxtPromObreros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnListadoActionPerformed
        ListEmpleados.setListData(arreglo1.getArregloEmpleados().toArray());
    }//GEN-LAST:event_BtnListadoActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed
      
        double[]aux=new double[3];
        aux=arreglo1.totalesXtipo();
        if(CmbTipos.getSelectedIndex()==1)
        {
             for (int i = 0; i < aux.length; i++) {
                TxtSumaSueldos.setText(String.valueOf(aux[0])); 
                break;
            }
            
        }
        else if(CmbTipos.getSelectedIndex()==2)
        {
            for (int i = 0; i < aux.length; i++) {
                TxtSumaSueldos.setText(String.valueOf(aux[1]));
                break;
                
            }
            
        }
        else if(CmbTipos.getSelectedIndex()==3)
        {
            for (int i = 0; i < aux.length; i++){           
            TxtSumaSueldos.setText(String.valueOf(aux[2]));
            break;}
        }
            
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void BtnTotalGralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTotalGralActionPerformed
        TxtTotal.setText(String.valueOf(arreglo1.totalGral()));
    }//GEN-LAST:event_BtnTotalGralActionPerformed

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        TxtMenorSueldo.setText(arreglo1.menorSueldo());
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnPromObrerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPromObrerosActionPerformed
        TxtPromObreros.setText(String.valueOf(arreglo1.promSueldoObreros()));
    }//GEN-LAST:event_BtnPromObrerosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnListado;
    private javax.swing.JButton BtnPromObreros;
    private javax.swing.JButton BtnTotalGral;
    private javax.swing.JComboBox<String> CmbTipos;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LblMenorSueldo;
    private javax.swing.JList ListEmpleados;
    private javax.swing.JTextField TxtMenorSueldo;
    private javax.swing.JTextField TxtPromObreros;
    private javax.swing.JTextField TxtSumaSueldos;
    private javax.swing.JTextField TxtTotal;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
