/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConexionJDBC;
import Modelo.Oferta;
import Modelo.Producto;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Denise
 */
public class RegistrarOferta extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarOferta
     */
    ConexionJDBC con= new ConexionJDBC();
    public RegistrarOferta() {
        initComponents();
        cagarComboProductos();
    }
    
    public void cagarComboProductos()
    {
        DefaultComboBoxModel modelo= new DefaultComboBoxModel();
        ArrayList<Producto> aux= con.obtenerProductos();
        for (Producto p : aux) {
            modelo.addElement(p);
        }
        cboProductos.setModel(modelo);       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JButton();
        TxtNormal = new javax.swing.JTextField();
        TxtOferta = new javax.swing.JTextField();
        TxtStock = new javax.swing.JTextField();
        TxtFecha = new javax.swing.JTextField();
        TxtVigencia = new javax.swing.JTextField();
        cboProductos = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("REGISTRAR OFERTA");

        jLabel2.setText("PRODUCTO");

        jLabel3.setText("PRECIO NORMAL");

        jLabel4.setText("PRECIO EN OFERTA");

        jLabel5.setText("STOCK DISPONIBLE");

        jLabel6.setText("FECHA INICIO DE OFERTA");

        jLabel7.setText("DIAS DE VIGENCIA");

        BtnRegistrar.setText("REGISTRAR");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        TxtNormal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNormalKeyPressed(evt);
            }
        });

        TxtOferta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtOfertaKeyPressed(evt);
            }
        });

        TxtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtStockKeyPressed(evt);
            }
        });

        TxtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtFechaKeyPressed(evt);
            }
        });

        TxtVigencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtVigenciaKeyPressed(evt);
            }
        });

        jButton1.setText("REPORTES");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(TxtOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboProductos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtNormal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TxtVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(BtnRegistrar))))))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(cboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(TxtNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtOferta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRegistrar))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNormalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNormalKeyPressed
        char press=evt.getKeyChar();
        if(Character.isLetter(press))
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
            TxtNormal.setText("");
        }
    }//GEN-LAST:event_TxtNormalKeyPressed

    private void TxtOfertaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtOfertaKeyPressed
        char press=evt.getKeyChar();
        if(Character.isLetter(press))
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
            TxtOferta.setText("");
        }
    }//GEN-LAST:event_TxtOfertaKeyPressed

    private void TxtStockKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtStockKeyPressed
         char press=evt.getKeyChar();
        if(Character.isLetter(press))
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
            TxtStock.setText("");
        }
    }//GEN-LAST:event_TxtStockKeyPressed

    private void TxtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtFechaKeyPressed
         char press=evt.getKeyChar();
        if(Character.isLetter(press))
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese fecha en formato dd/mm/aa");
            TxtFecha.setText("");
        }
    }//GEN-LAST:event_TxtFechaKeyPressed

    private void TxtVigenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtVigenciaKeyPressed
         char press=evt.getKeyChar();
        if(Character.isLetter(press))
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros");
            TxtVigencia.setText("");
        }
    }//GEN-LAST:event_TxtVigenciaKeyPressed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
       if(validarCamposVacios())
       {
           Producto p =(Producto)cboProductos.getSelectedItem();
           double normal=Double.parseDouble(TxtNormal.getText());
           double oferta=Double.parseDouble(TxtOferta.getText());
           int stock= Integer.parseInt(TxtStock.getText());
           String fecha=TxtFecha.getText();
           int vigencia=Integer.parseInt(TxtVigencia.getText());
           
           if(con.insertarOferta(new Oferta(0,p,normal,oferta,stock,fecha,vigencia)))
           {
               JOptionPane.showMessageDialog(rootPane, "Oferta registrada exitosamente");
           }
           else
           {
               JOptionPane.showMessageDialog(rootPane, "ERROR: No se pudo insertar la oferta");
           }
                   
           
           
       }
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new Reportes().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean validarCamposVacios()
    {
        boolean vale=true;
        if(TxtNormal.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese precio normal");
            vale=false;
        }
        if(TxtOferta.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese precio ofertado");
            vale=false;
        }
        if(TxtStock.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese stock disponible");
            vale=false;
        }
        if(TxtFecha.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese fecha de inicio de oferta");
            vale=false;
        }
        if(TxtVigencia.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Ingrese vigencia de la oferta");
            vale=false;
        }
        return vale;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarOferta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JTextField TxtFecha;
    private javax.swing.JTextField TxtNormal;
    private javax.swing.JTextField TxtOferta;
    private javax.swing.JTextField TxtStock;
    private javax.swing.JTextField TxtVigencia;
    private javax.swing.JComboBox cboProductos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
