
package proyectohotel;


public class FormularioReserva extends javax.swing.JFrame {
    
    ArreglosReservas nuevaReserva;

    public FormularioReserva() {
        initComponents();
        nuevaReserva= new ArreglosReservas();
        BtnReportes.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupTipoDeReserva = new javax.swing.ButtonGroup();
        LblReservas = new javax.swing.JLabel();
        LblHabitacion = new javax.swing.JLabel();
        TxtHabitacion = new javax.swing.JTextField();
        LblDias = new javax.swing.JLabel();
        CmbDias = new javax.swing.JComboBox<>();
        LblVigente = new javax.swing.JLabel();
        CheckVigente = new javax.swing.JCheckBox();
        LblNinios = new javax.swing.JLabel();
        CmbNinios = new javax.swing.JComboBox<>();
        LblConferencia = new javax.swing.JLabel();
        CheckConferencia = new javax.swing.JCheckBox();
        LblTipoReserva = new javax.swing.JLabel();
        RdoVacasiones = new javax.swing.JRadioButton();
        RdoNegocios = new javax.swing.JRadioButton();
        BtnConfirmar = new javax.swing.JButton();
        BtnReportes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LstListado = new javax.swing.JList();
        LblReportes = new javax.swing.JLabel();
        LblFacturacionTotal = new javax.swing.JLabel();
        TxtFacturacionTotal = new javax.swing.JTextField();
        LblcantReservas = new javax.swing.JLabel();
        LblReservasVacasiones = new javax.swing.JLabel();
        TxtReservasVacasiones = new javax.swing.JTextField();
        LblReservasNegocios = new javax.swing.JLabel();
        TxtReservasNegocios = new javax.swing.JTextField();
        LblListadoReservas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblReservas.setText("RESERVAS");

        LblHabitacion.setText("NUMERO DE HABITACION");

        LblDias.setText("CANTIDAD DE DIAS RESERVADOS");

        CmbDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "15", "20", "25", "30" }));

        LblVigente.setText("RESERVA VIGENTE");

        LblNinios.setText("CANTIDAD DE NIÑOS");

        CmbNinios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3", "4", "5" }));

        LblConferencia.setText("ASISTE A CONFERENCIA");

        LblTipoReserva.setText("TIPO DE RESERVA");

        btnGroupTipoDeReserva.add(RdoVacasiones);
        RdoVacasiones.setText("VACASIONES");
        RdoVacasiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoVacasionesActionPerformed(evt);
            }
        });

        btnGroupTipoDeReserva.add(RdoNegocios);
        RdoNegocios.setText("NEGOCIOS");
        RdoNegocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RdoNegociosActionPerformed(evt);
            }
        });

        BtnConfirmar.setText("CONFIRMAR RESERVA");
        BtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmarActionPerformed(evt);
            }
        });

        BtnReportes.setText("GENERAR REPORTES");
        BtnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReportesActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(LstListado);

        LblReportes.setText("REPORTES");

        LblFacturacionTotal.setText("FACTURACION TOTAL PREVISTA");

        LblcantReservas.setText("CANTIDAD DE RESERVAS DE CADA TIPO");

        LblReservasVacasiones.setText("VACASIONES");

        LblReservasNegocios.setText("NEGOCIOS");

        LblListadoReservas.setText("LISTADO DE RESERVAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblReservas)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblHabitacion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TxtHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblTipoReserva)
                                        .addGap(18, 18, 18)
                                        .addComponent(RdoVacasiones)))
                                .addGap(18, 18, 18)
                                .addComponent(RdoNegocios))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblDias)
                                .addGap(18, 18, 18)
                                .addComponent(CmbDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblVigente)
                                .addGap(18, 18, 18)
                                .addComponent(CheckVigente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnConfirmar)
                                .addGap(26, 26, 26)
                                .addComponent(BtnReportes))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblNinios)
                                .addGap(18, 18, 18)
                                .addComponent(CmbNinios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblConferencia)
                                .addGap(18, 18, 18)
                                .addComponent(CheckConferencia)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblReportes)
                            .addComponent(LblcantReservas)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(LblReservasVacasiones)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxtReservasVacasiones, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(LblReservasNegocios)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxtReservasNegocios))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(LblFacturacionTotal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TxtFacturacionTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LblListadoReservas))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtFacturacionTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblReservas)
                        .addGap(11, 11, 11)
                        .addComponent(LblListadoReservas)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LblTipoReserva)
                                    .addComponent(RdoVacasiones)
                                    .addComponent(RdoNegocios))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LblHabitacion)
                                    .addComponent(TxtHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LblDias)
                                    .addComponent(CmbDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblVigente)
                                            .addComponent(CheckVigente))
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LblNinios)
                                            .addComponent(CmbNinios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(LblConferencia))
                                    .addComponent(CheckConferencia)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblReportes)))
                        .addGap(27, 27, 27)
                        .addComponent(LblFacturacionTotal)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnConfirmar)
                            .addComponent(BtnReportes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LblcantReservas)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblReservasVacasiones)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtReservasVacasiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblReservasNegocios)
                        .addComponent(TxtReservasNegocios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RdoVacasionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoVacasionesActionPerformed
        CheckConferencia.setEnabled(false);
        CmbNinios.setEnabled(true);
    }//GEN-LAST:event_RdoVacasionesActionPerformed

    private void RdoNegociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RdoNegociosActionPerformed
        CheckConferencia.setEnabled(true);
        CmbNinios.setEnabled(false);
    }//GEN-LAST:event_RdoNegociosActionPerformed

    private void BtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmarActionPerformed
        int habitacion=Integer.parseInt(TxtHabitacion.getText());
        int cantDias=CmbDias.getSelectedIndex();
        boolean vigente=CheckVigente.isSelected();
         if(RdoVacasiones.isSelected())
         {
             int ninios=CmbNinios.getSelectedIndex();
         
          ReservaVacasiones nuevaVacasion= new ReservaVacasiones( habitacion,cantDias,vigente,ninios);
          nuevaReserva.agregarReserva(nuevaVacasion);
         }
         else
         {
             boolean conferencia= CheckConferencia.isSelected();
             ReservaNegocios nuevaNegocios = new ReservaNegocios(habitacion,cantDias,vigente,conferencia);
             nuevaReserva.agregarReserva(nuevaNegocios);
         }
         LstListado.setListData(nuevaReserva.getReservas().toArray());
         this.habilitarControles();
    }//GEN-LAST:event_BtnConfirmarActionPerformed

    private void BtnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReportesActionPerformed
       
        TxtFacturacionTotal.setText(String.valueOf(nuevaReserva.facturacionTotal()));
        
        int[]auxiliar= nuevaReserva.cantReservasXtipo();
        for (int i = 0; i < auxiliar.length; i++) {
            TxtReservasVacasiones.setText(String.valueOf(auxiliar[0]));
            break;
        }
        for (int i = 0; i < auxiliar.length; i++) {
            TxtReservasNegocios.setText(String.valueOf(auxiliar[1]));
            break;
        }
        
        
    }//GEN-LAST:event_BtnReportesActionPerformed

    
    public void habilitarControles(){
    RdoVacasiones.setSelected(false);
    RdoNegocios.setSelected(false);
    TxtHabitacion.setText("");
    CmbDias.setSelectedIndex(0);
    CheckVigente.setSelected(false);
    CmbNinios.setSelectedIndex(0);
   
    CheckConferencia.setSelected(false);
    
    BtnReportes.setEnabled(true);
    }
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmar;
    private javax.swing.JButton BtnReportes;
    private javax.swing.JCheckBox CheckConferencia;
    private javax.swing.JCheckBox CheckVigente;
    private javax.swing.JComboBox<String> CmbDias;
    private javax.swing.JComboBox<String> CmbNinios;
    private javax.swing.JLabel LblConferencia;
    private javax.swing.JLabel LblDias;
    private javax.swing.JLabel LblFacturacionTotal;
    private javax.swing.JLabel LblHabitacion;
    private javax.swing.JLabel LblListadoReservas;
    private javax.swing.JLabel LblNinios;
    private javax.swing.JLabel LblReportes;
    private javax.swing.JLabel LblReservas;
    private javax.swing.JLabel LblReservasNegocios;
    private javax.swing.JLabel LblReservasVacasiones;
    private javax.swing.JLabel LblTipoReserva;
    private javax.swing.JLabel LblVigente;
    private javax.swing.JLabel LblcantReservas;
    private javax.swing.JList LstListado;
    private javax.swing.JRadioButton RdoNegocios;
    private javax.swing.JRadioButton RdoVacasiones;
    private javax.swing.JTextField TxtFacturacionTotal;
    private javax.swing.JTextField TxtHabitacion;
    private javax.swing.JTextField TxtReservasNegocios;
    private javax.swing.JTextField TxtReservasVacasiones;
    private javax.swing.ButtonGroup btnGroupTipoDeReserva;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
